### ISSUE TITLE
RPICT3V1

### ISSUE THREAD

**Issue by turriert** [tlierdotfr/jeedom-plugin-rpict#1]
Bonjour Thomas,

J'ai fais l'acquisition d'un RPICT3V1. Il ne semble pas fonctionner avec votre Plugin.
Y a t'il une possibilité ?

Merci beaucoup !

Cordialement,

Thibaut

**Comment by tlierdotfr** [comment]
Hello Thibaut,
Quels sont les LOGs remontés par le deamon RPICT en mode DEBUG ?
Thomas

**Comment by turriert** [comment]
Thomas,

Ci-dessous mes Logs :

Rpict : 
```
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
[2020-11-27 15:45:11][ERROR] : Erreur sur la fonction deamon_start du plugin : Vous devez attendre au moins 45 secondes entre deux lancements du démon. Dernier lancement : 2020-11-27 15:44:38
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Traceback (most recent call last):
File "/var/www/html/plugins/rpict/ressources/rpict.py", line 289, in <module>
rpict.run()
File "/var/www/html/plugins/rpict/ressources/rpict.py", line 178, in run
frame = self._ser.readline()
File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 501, in read
'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/core/class/DB.class.php:40
Stack trace:
#0 /var/www/html/core/class/DB.class.php(40): PDO->__construct('mysql:host=loca...', 'jeedom', '2b5c6a1fd757a54', Array)
#1 /var/www/html/core/class/DB.class.php(50): DB::initConnection()
#2 /var/www/html/core/class/DB.class.php(82): DB::getConnection()
#3 /var/www/html/core/class/config.class.php(173): DB::Prepare('SELECT `key`,`v...', Array, 1)
#4 /var/www/html/core/class/translate.class.php(34): config::byKeys(Array)
#5 /var/www/html/core/class/translate.class.php(151): translate::getConfig('language', 'fr_FR')
#6 /var/www/html/core/class/translate.class.php(75): translate::getLanguage()
#7 /var/www/html/core/class/translate.class.php(54): translate::exec('{{Chauffage}}', '/var/www/html/c...', false)
#8 /var/www/html/core/class/translate.class.php(165): translate::sentence('Chauffage', '/var/www/html/c...', false)
#9 /var/www/html/core/config/jeedom.config.php(23): __('Chauffage' in /var/www/html/core/class/DB.class.php on line 40
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/core/class/DB.class.php:40
Stack trace:
#0 /var/www/html/core/class/DB.class.php(40): PDO->__construct('mysql:host=loca...', 'jeedom', '2b5c6a1fd757a54', Array)
#1 /var/www/html/core/class/DB.class.php(50): DB::initConnection()
#2 /var/www/html/core/class/DB.class.php(82): DB::getConnection()
#3 /var/www/html/core/class/config.class.php(173): DB::Prepare('SELECT `key`,`v...', Array, 1)
#4 /var/www/html/core/class/translate.class.php(34): config::byKeys(Array)
#5 /var/www/html/core/class/translate.class.php(151): translate::getConfig('language', 'fr_FR')
#6 /var/www/html/core/class/translate.class.php(75): translate::getLanguage()
#7 /var/www/html/core/class/translate.class.php(54): translate::exec('{{Chauffage}}', '/var/www/html/c...', false)
#8 /var/www/html/core/class/translate.class.php(165): translate::sentence('Chauffage', '/var/www/html/c...', false)
#9 /var/www/html/core/config/jeedom.config.php(23): __('Chauffage' in /var/www/html/core/class/DB.class.php on line 40
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/var/www/html/plugins/rpict/ressources/rpict.py", line 151, in target
self.process = subprocess.Popen(self.cmd + send_data_bak, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
TypeError: execv() arg 2 must contain only strings
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Traceback (most recent call last):
File "/var/www/html/plugins/rpict/ressources/rpict.py", line 289, in <module>
rpict.run()
File "/var/www/html/plugins/rpict/ressources/rpict.py", line 178, in run
frame = self._ser.readline()
File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 501, in read
'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
[2020-11-27 16:52:40][ERROR] : Erreur sur la fonction deamon_start du plugin : Vous devez attendre au moins 45 secondes entre deux lancements du démon. Dernier lancement : 2020-11-27 16:52:21
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Error opening serial
Terminating...
[2020-11-27 16:56:51][ERROR] : Impossible de lancer le démon RPICT, vérifiez le port
[2020-11-27 16:57:05][ERROR] : Erreur sur la fonction deamon_start du plugin : Vous devez attendre au moins 45 secondes entre deux lancements du démon. Dernier lancement : 2020-11-27 16:56:39
[2020-11-27 16:57:20][ERROR] : Erreur sur la fonction deamon_start du plugin : Vous devez attendre au moins 45 secondes entre deux lancements du démon. Dernier lancement : 2020-11-27 16:56:39
[2020-11-27 16:57:21][ERROR] : Erreur sur la fonction deamon_start du plugin : Vous devez attendre au moins 45 secondes entre deux lancements du démon. Dernier lancement : 2020-11-27 16:56:39
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
```

Rpict_deamon : 
```
2020-11-27 16:20:32,570 INFO logger started in INFO mode
2020-11-27 16:20:32,570 INFO Try to open Rpict link /dev/ttyAMA0 with speed 38400
2020-11-27 16:20:32,571 INFO Rpict link successfully opened
2020-11-27 16:20:43,890 INFO Try to close Rpict link
2020-11-27 16:20:43,895 INFO Rpict link successfully closed
```

Rpict_update : 
```
Lancement de l'installation/mise à jour des dépendances Téléinfo
Raffraichissement du système
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 https://deb.nodesource.com/node_12.x buster InRelease
Reading package lists...
Installation de la librairie ftdi pour modem 2 compteurs
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-ftdi
Reading package lists...
Building dependency tree...
Reading state information...
python-ftdi1 is already the newest version (1.4-1+b2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pylibftdi
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e0a10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e0a70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e0ab0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e0b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e0c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb57e0cf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
could not install  - abort
```

Merci beaucoup !

**Comment by tlierdotfr** [comment]
On dirait qu'il y a eu une erreur lors de l'installation des dépendances et du coup le deamon n'arrive pas à ouvrir la liaison série.

Il faudrait essayer d'exécuter en ligne de commande sur la Rapsberry la commande ci dessous pour voir ce qui pose problème lors de l'installation manuelle de la dépendance :
`sudo pip install pylibftdi`

**Comment by turriert** [comment]
Voilà mon résultat : 
```
pi@raspberrypi:~ $  sudo pip install pylibftdi
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pylibftdi
  Downloading https://files.pythonhosted.org/packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl
Installing collected packages: pylibftdi
Successfully installed pylibftdi-0.19.0
```

et mes Logs : 
Rpict :
```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/var/www/html/plugins/rpict/ressources/rpict.py", line 151, in target
self.process = subprocess.Popen(self.cmd + send_data_bak, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
TypeError: execv() arg 2 must contain only strings
```

Rpict_deamon :
```
2020-11-28 15:22:09,062 INFO logger started in INFO mode
2020-11-28 15:22:09,063 INFO Try to open Rpict link /dev/ttyAMA0 with speed 38400
2020-11-28 15:22:09,063 INFO Rpict link successfully opened
2020-11-28 15:22:21,252 WARNING Thread not alive
```

**Comment by tlierdotfr** [comment]
C'est déjà un peu mieux on dirait mais par contre le deamon n'a pas l'air de recevoir ce qu'il faut.
Il faudrait mettre le plugin en log DEBUG et me renvoyer des LOGs pour voir plus de détails.

Pourrais tu aussi lancer cette commande sur le raspberry alors que le plugin est désactivé pour voir ce que renvoie le RPIC sur la liaison série ?
`cat /dev/ttyAMA0`

**Comment by turriert** [comment]
Thomas,

Mode debug : 
**Rpict** : 
```
[2020-11-30 15:11:25][INFO] : Début d'activation du plugin
[2020-11-30 15:11:26][INFO] : Info sur le démon : {"launchable_message":"","launchable":"nok","state":"nok","log":"nok","auto":0}
[2020-11-30 15:11:26][DEBUG] : Lancement de : /var/www/html/core/class/../../core/php/jeePlugin.php  plugin_id=rpict function=install callInstallFunction=1
[2020-11-30 15:11:27][INFO] : Vérification de l'état du service : NOK
Init deamon ...
pidfile : /tmp/rpict.pid
Starting deamon...
Terminating...
[2020-11-30 15:13:41][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.18 / ch10=0.000 / ch11=0.00 / ch14=0.20 / ch15=0.000 / nid=11 / ch1=0.00 / ch2=1.86 / ch3=2056.44 / ch4=0.21 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=4.81 / ch9=0.22 /
[2020-11-30 15:13:46][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.18 / ch10=0.000 / ch11=0.00 / ch14=0.14 / ch15=0.000 / nid=11 / ch1=0.05 / ch2=1.59 / ch3=2049.98 / ch4=0.18 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=2.88 / ch9=0.22 /
[2020-11-30 15:13:51][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.12 / ch10=0.000 / ch11=0.00 / ch14=0.16 / ch15=0.000 / nid=11 / ch1=0.02 / ch2=1.26 / ch3=2037.55 / ch4=0.14 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.19 /
[2020-11-30 15:13:57][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.06 / ch10=0.000 / ch11=0.00 / ch14=0.12 / ch15=0.000 / nid=11 / ch1=0.16 / ch2=1.74 / ch3=2056.75 / ch4=0.19 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.87 / ch9=0.22 /
[2020-11-30 15:14:02][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=2.76 / ch10=0.000 / ch11=0.00 / ch14=0.23 / ch15=0.000 / nid=11 / ch1=0.05 / ch2=2.10 / ch3=2053.56 / ch4=0.23 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.93 / ch9=0.27 /
[2020-11-30 15:14:07][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=2.76 / ch10=0.000 / ch11=0.00 / ch14=0.25 / ch15=0.000 / nid=11 / ch1=-0.16 / ch2=1.27 / ch3=2049.51 / ch4=0.14 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.09 /
[2020-11-30 15:14:12][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=2.76 / ch10=0.000 / ch11=-0.00 / ch14=0.18 / ch15=0.000 / nid=11 / ch1=0.03 / ch2=0.30 / ch3=380.37 / ch4=0.18 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=1.02 / ch9=0.16 /
[2020-11-30 15:14:17][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.24 / ch10=0.000 / ch11=0.00 / ch14=0.18 / ch15=0.000 / nid=11 / ch1=0.02 / ch2=0.23 / ch3=377.32 / ch4=0.14 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.14 /
[2020-11-30 15:14:22][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.84 / ch10=0.000 / ch11=0.00 / ch14=0.16 / ch15=0.000 / nid=11 / ch1=0.02 / ch2=0.32 / ch3=373.27 / ch4=0.19 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=4.02 / ch9=0.18 /
[2020-11-30 15:14:28][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.84 / ch10=0.000 / ch11=0.00 / ch14=0.16 / ch15=0.000 / nid=11 / ch1=-0.01 / ch2=0.26 / ch3=370.75 / ch4=0.16 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.16 /
[2020-11-30 15:14:33][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.78 / ch10=0.000 / ch11=0.00 / ch14=0.22 / ch15=0.000 / nid=11 / ch1=0.03 / ch2=0.33 / ch3=368.94 / ch4=0.21 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.18 /
[2020-11-30 15:14:38][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.78 / ch10=0.000 / ch11=0.00 / ch14=0.18 / ch15=0.000 / nid=11 / ch1=0.02 / ch2=0.20 / ch3=371.87 / ch4=0.12 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.19 /
[2020-11-30 15:14:43][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.30 / ch10=0.000 / ch11=0.00 / ch14=0.09 / ch15=0.000 / nid=11 / ch1=-0.02 / ch2=0.29 / ch3=367.49 / ch4=0.18 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.18 /
[2020-11-30 15:14:48][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.24 / ch10=0.000 / ch11=0.00 / ch14=0.14 / ch15=0.000 / nid=11 / ch1=0.02 / ch2=0.26 / ch3=371.51 / ch4=0.16 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=2.97 / ch9=0.20 /
[2020-11-30 15:14:53][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.36 / ch10=0.000 / ch11=0.00 / ch14=0.12 / ch15=0.000 / nid=11 / ch1=0.01 / ch2=0.23 / ch3=368.95 / ch4=0.14 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.90 / ch9=0.18 /
[2020-11-30 15:14:59][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.36 / ch10=0.000 / ch11=0.00 / ch14=0.12 / ch15=0.000 / nid=11 / ch1=0.01 / ch2=0.26 / ch3=373.39 / ch4=0.16 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.16 /
[2020-11-30 15:15:04][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.36 / ch10=0.000 / ch11=0.00 / ch14=0.12 / ch15=0.000 / nid=11 / ch1=-0.04 / ch2=0.26 / ch3=372.03 / ch4=0.16 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.14 /
[2020-11-30 15:15:09][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.30 / ch10=0.000 / ch11=0.00 / ch14=0.18 / ch15=0.000 / nid=11 / ch1=-0.00 / ch2=0.20 / ch3=372.68 / ch4=0.12 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.16 /
[2020-11-30 15:15:14][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.72 / ch10=0.000 / ch11=0.00 / ch14=0.09 / ch15=0.000 / nid=11 / ch1=-0.01 / ch2=0.20 / ch3=372.84 / ch4=0.12 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.09 /
[2020-11-30 15:15:19][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.60 / ch10=0.000 / ch11=0.00 / ch14=0.16 / ch15=0.000 / nid=11 / ch1=-0.02 / ch2=0.27 / ch3=378.97 / ch4=0.16 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.09 /
[2020-11-30 15:15:24][DEBUG] : Reception de : api=WFHhm0UZ22OcyJbGcFIN36N2S5659U5d / ch12=0.00 / ch13=0.60 / ch10=0.000 / ch11=0.00 / ch14=0.14 / ch15=0.000 / nid=11 / ch1=-0.00 / ch2=0.09 / ch3=378.69 / ch4=0.05 / ch5=0.000 / ch6=0.00 / ch7=0.00 / ch8=0.97 / ch9=0.12 /
```

**Rpict_deamon** : 
```
2020-11-30 14:11:47,701 INFO logger started in INFO mode
2020-11-30 14:11:47,702 INFO Try to open Rpict link /dev/ttyAMA0 with speed 38400
2020-11-30 14:11:47,703 INFO Rpict link successfully opened
2020-11-30 14:12:51,908 INFO Try to close Rpict link
2020-11-30 14:12:51,910 INFO Rpict link successfully closed
2020-11-30 14:13:04,609 INFO logger started in INFO mode
2020-11-30 14:13:04,609 INFO Try to open Rpict link /dev/ttyAMA0 with speed 38400
2020-11-30 14:13:04,610 INFO Rpict link successfully opened
```

Voici ce que j'obtiens lorsque je me met en **lecture directe** : 
```
pi@raspberrypi:~ $ stty -F /dev/ttyAMA0 raw speed 38400
38400
pi@raspberrypi:~ $ cat /dev/ttyAMA0
11 0.10 1.23 1980.48 0.14 0.000 0.00 0.00 0.97 0.18 0.000 -0.00 0.00 1.86 0.19 0.000
11 0.04 0.81 1996.29 0.09 0.000 0.00 0.00 0.97 0.16 0.000 -0.00 0.00 1.93 0.09 0.000
11 -0.01 1.40 1987.03 0.16 0.000 0.00 0.00 0.97 0.12 0.000 -0.00 0.00 1.93 0.12 0.000
11 0.01 1.54 1977.46 0.18 0.000 0.00 0.00 0.97 0.16 0.000 -0.00 0.00 1.93 0.16 0.000
11 -0.06 1.55 1998.37 0.18 0.000 0.00 0.00 0.97 0.14 0.000 -0.00 0.00 1.93 0.18 0.000
```
Voici les configs de mon RPICT3V1 : 
```
[main]
format = 3
nodeid = 11
polling = 5000
vest = 230
xpFREQ = 50
Ncycle = 20
kcal = 83.33 83.33 83.33 1. 1. 1. 1. 545.0
phasecal = 0
debug = 0
```

Merci beaucoup !

**Comment by tlierdotfr** [comment]
Hello Thibaut,

Les LOGs DEBUG ont l'air bon, on voit des valeurs qui changent et qui ont l'air de correspondre au même ordre de grandeur que les valeurs que tu as en regardant la lecture directe de la liaison série.

Du coup normalement il ne te reste plus qu'a créer un équipement via la page du plugin RPICT et lui mettre comme identifiant le nodeid de ta carte (=> 11). 
Coche bien la création auto des commandes et normalement tu devrais voir apparaitre les 15 commandes qui correspondent aux 15 channels de données renvoyés par le module RPICT.

**Comment by turriert** [comment]
Thomas, 

Lorsque je vais dans les objets, cela me marque "aucun objet trouvé".

Je suis ok pour trouver un créneau pour effectuer une visio avec partage d'écran afin de trouver le problème si tu le souhaites ?

**Comment by tlierdotfr** [comment]
Il faut dans Jeedom aller sur l'onglet Plugin / Protocole Domotique / RPICT7V1.
Ensuite tu dois pouvoir cliquer sur Ajouter pour créer l'objet / le module.

**Comment by turriert** [comment]
Thomas, 

Voici mes paramètres : 
![Paramètres](https://user-images.githubusercontent.com/75133937/100877277-d3f30000-34a8-11eb-85f2-7e90754a52b1.JPG)

Voici ce que j'obtiens lorsque je vais sur Plugin / Protocole Domotique / RPICT7V1 : 
![Ajout d'objet](https://user-images.githubusercontent.com/75133937/100877400-03097180-34a9-11eb-8a81-bf394c63c50c.JPG)

Merci !

**Comment by tlierdotfr** [comment]
Quelle version de Jeedom core as tu ?

**Comment by tlierdotfr** [comment]
Hello Thibaut,

Merci pour la remontée.
Le pb vient du fait que je n'ai jamais fait l'upgrade clean pour rendre compatible le plugin pour la version 4 de Jeedom (je suis encore en V3 de mon coté).
Je viens de push une modif en Beta. Il faut que tu autorise les Beta dans la configuration générale de Jeedom et que tu mettes à jour avec la Beta.

Il se peut qu'il y ait d'autres problèmes d'affichage mais j'espère déjà que ça te débloquera.

Thomas

**Comment by turriert** [comment]
Bonjour Thomas,

ça y est cela fonctionne !! Merci beaucoup !

Effectivement je suis en v4 j'ai donc installé cela en beta.
Est-ce que du coup le rpict devient compatible avec le plugin "Suivi Conso" ?

Merci beaucoup de ton aide !

**Comment by tlierdotfr** [comment]
Hello Thibaut,

Top, super nouvelle 💯 
Tu es du coup mon Beta Testeur pour la future évolution V4 ;-)
N'hésite pas à me remonter si jamais il y a des petits bug d'affichage.

Concernant la compatibilité avec le plugin SuiviConso oui c'est le cas mais il faut faire un réglage particulier lors de la création de l'équipement sur le plugin SuiviConso (=> "je n'ai que la puissance") et indiquer ensuite la référence des commandes du RPICT.
![image](https://user-images.githubusercontent.com/11616982/101177273-ea838d80-3647-11eb-9120-bd0fa6e147e3.png)


Thomas

**Comment by turriert** [comment]
C'est un plaisir d'être le Beta testeur 👍 
Pas de soucis, si j'ai des soucis je te les fais remonter mais à première vu tout se passe bien pour le moment !!!
Merci beaucoup !

**Comment by turriert** [comment]
Bonjour Thomas,

Je ne sais pas si tu vas lire ce post..

Ton plugin fonctionne maintenant à merveille !!
Je ne sais pas si tu l'as fait mais je souhaiterai configurer mon plugin Suivi Conso avec ton plugin. tout en sachant que je n'ai que la puissance instantanée d'affichée.

As-tu déjà paramétré ce plugin ? si oui comment ?

Je te remercie !

Thibaut
